# Generated by Django 5.1 on 2025-08-02 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inform_me_requests', to='backend.product')),
                ('product_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inform_me_requests', to='backend.productoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inform_me_requests', to='backend.user')),
            ],
            options={
                'verbose_name': 'Inform Me Request',
                'verbose_name_plural': 'Inform Me Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
