# Generated by Django 5.1 on 2025-08-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_informme'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=10)),
                ('current_version', models.CharField(max_length=20)),
                ('current_build', models.IntegerField()),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('has_update', models.BooleanField()),
                ('is_forced', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('version_name', models.CharField(help_text='e.g., 1.2.3', max_length=20)),
                ('version_code', models.IntegerField(help_text='Build number')),
                ('min_supported_version', models.CharField(help_text='Minimum version required', max_length=20)),
                ('min_supported_code', models.IntegerField(help_text='Minimum build number required')),
                ('is_force_update', models.BooleanField(default=False, help_text='Force users to update')),
                ('update_message', models.TextField(blank=True, help_text='Custom update message')),
                ('release_notes', models.TextField(blank=True, help_text="What's new in this version")),
                ('store_url', models.URLField(help_text='App store download URL')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('platform', 'version_name')},
            },
        ),
    ]
