# Generated by Django 5.1 on 2025-08-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_updatechecklog_appversion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateCheckLog',
        ),
        migrations.AlterModelOptions(
            name='appversion',
            options={'ordering': ['-created_at'], 'verbose_name': 'App Version', 'verbose_name_plural': 'App Versions'},
        ),
        migrations.AlterField(
            model_name='appversion',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active versions will be used for update checks'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='is_force_update',
            field=models.BooleanField(default=False, help_text='Force all users to update (regardless of minimum version)'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='min_supported_version',
            field=models.CharField(help_text='Minimum version required (users below this will be forced to update)', max_length=20),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], help_text='Select platform (Android or iOS)', max_length=10),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='release_notes',
            field=models.TextField(blank=True, help_text="What's new in this version (shown in update dialog)"),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='update_message',
            field=models.TextField(blank=True, default='A new version is available with exciting new features!', help_text='Custom message shown to users'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='version_code',
            field=models.IntegerField(help_text='Build number (e.g., 1, 2, 3...)'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='version_name',
            field=models.CharField(help_text='Version number (e.g., 2.0.0, 3.1.5)', max_length=20),
        ),
    ]
