"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
import requests

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w96($5)b9+2lh*44gh^tbur1f!yx(td78_&uf2!(26msmz4ep8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    "corsheaders",
    'backend'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'postgres',  # You can change this if you created a different DB
#         'USER': 'super',
#         'PASSWORD': 'clickWELL_postgresdb',
#         'HOST': 'Clickwelladmin-4622.postgres.pythonanywhere-services.com',
#         'PORT': '14622',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
  #  {
   #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    #},
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

TIME_ZONE =  'Asia/Kolkata'



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = '/home/Clickwelladmin/DjangoAdmin/clickwell-backend/core/static'

JAZZMIN_SETTINGS = {
    "welcome_sign": "Welcome to the ClickWell Admin Panel",
    "copyright": "ClickWell Ltd",

}

#JAZZMIN_UI_TWEAKS = {
 #   "theme": "darkly",
#}



MEDIA_URL = '/media/'
MEDIA_ROOT =os.path.join(BASE_DIR,'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TEMPLATES_BASE_URL = 'https://clickwelladmin.pythonanywhere.com' #https://127.0.0.1:8000


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-relay.brevo.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'clickwell2005@gmail.com'
EMAIL_HOST_PASSWORD = 'TwQ5OsXc3VASmhvj'

CORS_ALLOWED_ORIGINS = [
    "http://10.0.2.2:8000",
    "http://127.0.0.1:8000",
    "http://89.117.157.199",
    "http://192.168.29.118",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'backend.authentication.TokenAuthentication',
        'rest_framework.permissions.AllowAny',
    ]
}

CF_ID = 'TEST372457e2b0ea32699ebf9e3ce1754273'
CF_KEY = 'TEST4def5fbf0e70cfb1833b9555e718ae457444cf2c'

FSMS_KEY = "fkN495zDPUhQQOTHhWNAto9tXEQMZc6RWqxEBmIZhrDHW4bvryTZm2f3y9Bi"

FCM_KEY = 'AAAAjFPAKtE:APA91bEbKDya5-EOBiepTXmjTOXA_DS-vytnxKJocUetGGoMZOz4PgUFVexOMToudGPsv19rVQK_autbOYjy88QCcTgZ7SgzSfwQYuDQ_FwzgQ4yynx30yrsLQi-YqmyZF0TYy7yaLcv'

#SERVICE_ACCOUNT_FILE = os.path.join(BASE_DIR, '/home/Clickwelladmin/DjangoAdmin/clickwell-backend/core/credentials/serviceAccountKey.json')
SERVICE_ACCOUNT_FILE = os.path.join(BASE_DIR,'/home/Clickwelladmin/DjangoAdmin/clickwell-backend/core/credentials/serviceAccountKey.json')

PROJECT_ID = 'clickwell-78742'

# TODO ##TESTING MODE
#RAZORPAY_KEY_ID = "rzp_test_YCWjqfR1L6Ef6w"
#RAZORPAY_KEY_SECRET = "REXlVFdOTSImGL1OZCm8VZVl"

#TODO #PRODUCTION MODE
RAZORPAY_KEY_ID = "rzp_live_du1Zpz1zCpez7f"
RAZORPAY_KEY_SECRET = "qOoISkBxU3zhc2JYHYUJLnub"

# 🔹 APNs Certificate Configuration for PythonAnywhere
APNS_CA_CERT_PATH = os.path.join(BASE_DIR, "core", "USERTrust_RSA.crt")

# 🔹 Ensure requests module uses the correct CA certificate
requests_session = requests.Session()
requests_session.verify = APNS_CA_CERT_PATH

# 🔹 If using pyapns2 for push notifications, configure the certificate
try:
    from apns2.client import APNsClient
    from apns2.credentials import TokenCredentials

    APNS_CERT_PATH = "/home/Clickwelladmin/DjangoAdmin/clickwell-backend/core/USERTrust_RSA.crt"

    credentials = TokenCredentials(auth_key_path="path/to/AuthKey.p8")
    apns_client = APNsClient(
        credentials=credentials,
        use_sandbox=False,
        root_certificates=APNS_CERT_PATH
    )
except ImportError:
    apns_client = None  # Ensure this doesn't break Django if pyapns2 isn't installed

# Logging for APNs
import logging
logger = logging.getLogger(__name__)
logger.info(f"APNs Certificate Path: {APNS_CA_CERT_PATH}")



